### ISSUE TITLE
Connection Reset by Peer when using example code

### ISSUE THREAD

**Issue by rescuehero** [thingsboard/thingsboard-python-rest-client#14]
used tb_rest_client: pip install tb_rest_client
as well as: pip install tb_rest_client32
(V1.2)

tested operating systems:
Windows10 and Ubuntu 18.04

code:
```
import logging
# Importing models and REST client class from Community Edition version
from tb_rest_client.rest_client_ce import *
from tb_rest_client.rest import ApiException
#from tb_rest_client32.rest_client_ce import *
#from tb_rest_client32.rest import ApiException

logging.basicConfig(level=logging.DEBUG,
                    format='%(asctime)s - %(levelname)s - %(module)s - %(lineno)d - %(message)s',
                    datefmt='%Y-%m-%d %H:%M:%S')

# ThingsBoard REST API URL
url = "http://XXX:8080"

# Default Tenant Administrator credentials
username = "tenant@thingsboard.org"
password = "tenant"

# Creating the REST client object with context manager to get auto token refresh
with RestClientCE(base_url=url) as rest_client:
    try:
        # Auth with credentials
        rest_client.login(username=username, password=password)
        user = rest_client.get_user()
        print(user)
    except ApiException as e:
        logging.exception(e)
```

behavior:
requests.exceptions.ConnectionError: ('Connection aborted.', ConnectionResetError(10054, 'Eine vorhandene Verbindung wurde vom Remotehost geschlossen', None, 10054, None))
raise ConnectionError(err, request=request)
requests.exceptions.ConnectionError: ('Connection aborted.', ConnectionResetError(104, 'Connection reset by peer'))

expected behavior:
no Exception and simple login.

test with curl:
```
curl -X POST --header "Content-Type: application/json" --header "Accept: application/json" -d "{\"username\":\"tenant@thingsboard.org\", \"password\":\"tenant\"}" "http://XXX.com:8080/api/auth/login"
```
returns the token

> (you could use the \" in your guide for curl to make it natively work with windows which is default for many first time users out there I guess)

audit log:
shows success on login with python client:
```
  "browser": "Python Requests 2.25",
  "os": "Other",
  "device": "Other"
```

sysadmin-panel:
base-url is still localhost - should this be edited?

**Comment by samson0v** [comment]
Hi @rescuehero, please update the rest-client to the newest version (1.3) via master branch or ```pip install tb-rest-client```.
If it doesn't help, provide new info about your issue.
Thanks!

**Comment by rescuehero** [comment]
After installing on a freshly created venv, i get:
```
Traceback (most recent call last):
  File "export_to_csv.py", line 26, in <module>
    from tb_rest_client.rest_client_ce import *
  File "F:\venv-folder\lib\site-packages\tb_rest_client\rest_client_ce.py", line 17, in <module>
    from tb_rest_client.rest_client_base import *
  File "F:\venv-folder\lib\site-packages\tb_rest_client\rest_client_base.py", line 24, in <module>
    from tb_rest_client.api.api_ce import *
  File "F:\venv-folder\lib\site-packages\tb_rest_client\api\api_ce\__init__.py", line 1, in <module>
    from .o_auth_2_config_template_controller_api import OAuth2ConfigTemplateControllerApi
  File "F:\venv-folder\lib\site-packages\tb_rest_client\api\api_ce\o_auth_2_config_template_controller_api.py", line 20, in <module>
    from tb_rest_client.api_client import ApiClient
  File "F:\venv-folder\lib\site-packages\tb_rest_client\api_client.py", line 32, in <module>
    import tb_rest_client.models.models_ce
  File "F:\venv-folder\lib\site-packages\tb_rest_client\models\models_ce\__init__.py", line 3, in <module>
    from .admin_settings_id import AdminSettingsId
  File "F:\venv-folder\lib\site-packages\tb_rest_client\models\models_ce\admin_settings_id.py", line 17, in <module>
    from . import EntityId
ImportError: cannot import name 'EntityId' from partially initialized module 'tb_rest_client.models.models_ce' (most likely due to a circular import) (F:\venv-folder\lib\site-packages\tb_rest_client\models\models_ce\__init__.py)
```

**Comment by samson0v** [comment]
Hi @rescuehero, the bug was fixed, please update the rest-client to the newest version via the master branch

**Comment by rescuehero** [comment]
`Traceback (most recent call last):
  File "XXX\lib\site-packages\urllib3\connectionpool.py", line 699, in urlopen
    httplib_response = self._make_request(
  File "XXX\lib\site-packages\urllib3\connectionpool.py", line 445, in _make_request
    six.raise_from(e, None)
  File "<string>", line 3, in raise_from
  File "XXX\lib\site-packages\urllib3\connectionpool.py", line 440, in _make_request
    httplib_response = conn.getresponse()
  File "C:\Program Files\Python38\lib\http\client.py", line 1322, in getresponse
    response.begin()
  File "C:\Program Files\Python38\lib\http\client.py", line 303, in begin
    version, status, reason = self._read_status()
  File "C:\Program Files\Python38\lib\http\client.py", line 264, in _read_status
    line = str(self.fp.readline(_MAXLINE + 1), "iso-8859-1")
  File "C:\Program Files\Python38\lib\socket.py", line 669, in readinto
    return self._sock.recv_into(b)
ConnectionResetError: [WinError 10054] Eine vorhandene Verbindung wurde vom Remotehost geschlossen

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "XXX\lib\site-packages\requests\adapters.py", line 439, in send
    resp = conn.urlopen(
  File "XXX\lib\site-packages\urllib3\connectionpool.py", line 755, in urlopen
    retries = retries.increment(
  File "XXX\lib\site-packages\urllib3\util\retry.py", line 532, in increment
    raise six.reraise(type(error), error, _stacktrace)
  File "XXX\lib\site-packages\urllib3\packages\six.py", line 769, in reraise
    raise value.with_traceback(tb)
  File "XXX\lib\site-packages\urllib3\connectionpool.py", line 699, in urlopen
    httplib_response = self._make_request(
  File "XXX\lib\site-packages\urllib3\connectionpool.py", line 445, in _make_request
    six.raise_from(e, None)
  File "<string>", line 3, in raise_from
  File "XXX\lib\site-packages\urllib3\connectionpool.py", line 440, in _make_request
    httplib_response = conn.getresponse()
  File "C:\Program Files\Python38\lib\http\client.py", line 1322, in getresponse
    response.begin()
  File "C:\Program Files\Python38\lib\http\client.py", line 303, in begin
    version, status, reason = self._read_status()
  File "C:\Program Files\Python38\lib\http\client.py", line 264, in _read_status
    line = str(self.fp.readline(_MAXLINE + 1), "iso-8859-1")
  File "C:\Program Files\Python38\lib\socket.py", line 669, in readinto
    return self._sock.recv_into(b)
urllib3.exceptions.ProtocolError: ('Connection aborted.', ConnectionResetError(10054, 'Eine vorhandene Verbindung wurde vom Remotehost geschlossen', None, 10054, None))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "F:/coding/Python/smartfilter/datahandling/export_to_csv.py", line 49, in <module>
    rest_client.login(username=username, password=password)
  File "XXX\lib\site-packages\tb_rest_client\rest_client_base.py", line 83, in login
    token_json = post(self.base_url + "/api/auth/login", json={"username": username, "password": password},
  File "XXX\lib\site-packages\requests\api.py", line 117, in post
    return request('post', url, data=data, json=json, **kwargs)
  File "XXX\lib\site-packages\requests\api.py", line 61, in request
    return session.request(method=method, url=url, **kwargs)
  File "XXX\lib\site-packages\requests\sessions.py", line 542, in request
    resp = self.send(prep, **send_kwargs)
  File "XXX\lib\site-packages\requests\sessions.py", line 655, in send
    r = adapter.send(request, **kwargs)
  File "XXX\lib\site-packages\requests\adapters.py", line 498, in send
    raise ConnectionError(err, request=request)
requests.exceptions.ConnectionError: ('Connection aborted.', ConnectionResetError(10054, 'Eine vorhandene Verbindung wurde vom Remotehost geschlossen', None, 10054, None))

Process finished with exit code 1
`

still the same issue with tb-rest-client-1.3.2

**Comment by rescuehero** [comment]
@zbeacon @samson0v

**Comment by rescuehero** [comment]
When using get directly:
```
full_address=server_address + "/api/plugins/telemetry/DEVICE/" + DEVICE_ID + "/" + keys + "/timeseries"
print(full_address)
response = requests.get(
    full_address
)
```

I also get the same error - an error directly in the python-backend can be negated.
Do you know how to resolve the issue?

Right now I am directly exporting the data from the SQL-DB but would love to use the python-API to do so and to be able to use your filtering functions provided by the API directly.

**Comment by samson0v** [comment]
Hi @rescuehero, update your rest client to the newest version via the master branch and let us know if it helps.
