### ISSUE TITLE
[Bug] - PE version of the client doesn't use the correct api_pe/asset_controller_api.py

### ISSUE THREAD

**Issue by tokmakoff** [thingsboard/thingsboard-python-rest-client#156]
When using the PE version of the library to make assets, it tries to use the CE version of `asset_controller_api.py` as that is the default which is configured in `rest_client_base.py`.

The controllers that need to be overridden for the PE version are setup in [here](https://github.com/thingsboard/thingsboard-python-rest-client/blob/24fcd2a1b71f313fbf6c0512f5de9f956ff45475/tb_rest_client/api/api_pe/__init__.py):

The PE version of AssetController is missing such an assignment, so the following needs to be added to the [__init__](https://github.com/thingsboard/thingsboard-python-rest-client/blob/24fcd2a1b71f313fbf6c0512f5de9f956ff45475/tb_rest_client/api/api_pe/__init__.py) script

`from .asset_controller_api import AssetControllerApi`

Without this, the CE version is used and then there are errors thrown related to unexpected parameters in the call (e.g. entity_group_ids)

**Comment by tokmakoff** [comment]
No, I was wrong on the solution.  The PE AssetController is being imported correctly, but I am still seeing the CE version of the AssetController being called...

**Comment by tokmakoff** [comment]
`Traceback (most recent call last):
  File "myCode.py", line 498, in <module>
    main()
  File "myCode.py", line 116, in main
    myAsset = rest_client.save_asset(myAsset, customer_assets_group.id.id)
                             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/anaconda3/lib/python3.12/site-packages/tb_rest_client/rest_client_pe.py", line 104, in save_asset
    return self.asset_controller.save_asset_using_post(body=body, entity_group_id=entity_group_id, entity_group_ids=entity_group_ids)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/anaconda3/lib/python3.12/site-packages/tb_rest_client/api/api_ce/asset_controller_api.py", line 1757, in save_asset_using_post
    (data) = self.save_asset_using_post_with_http_info(**kwargs)  # noqa: E501
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/anaconda3/lib/python3.12/site-packages/tb_rest_client/api/api_ce/asset_controller_api.py", line 1786, in save_asset_using_post_with_http_info
    raise TypeError(
TypeError: Got an unexpected keyword argument 'entity_group_id' to method save_asset_using_post`

**Comment by tokmakoff** [comment]
I think this issue has already been reported at #151.
