### ISSUE TITLE
NameError: name 'TenantProfile' is not defined

### ISSUE THREAD

**Issue by maksonlee** [thingsboard/thingsboard-python-rest-client#25]
Traceback (most recent call last):
  File "create-device.py", line 2, in <module>
    from tb_rest_client.rest_client_ce import *
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 655, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 618, in _load_backward_compatible
  File "<frozen zipimport>", line 259, in load_module
  File "/home/administrator/.pyenv/versions/3.8.11/lib/python3.8/site-packages/tb_rest_client-1.1.1-py3.8.egg/tb_rest_client/rest_client_ce.py", line 17, in <module>
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 655, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 618, in _load_backward_compatible
  File "<frozen zipimport>", line 259, in load_module
  File "/home/administrator/.pyenv/versions/3.8.11/lib/python3.8/site-packages/tb_rest_client-1.1.1-py3.8.egg/tb_rest_client/rest_client_base.py", line 32, in <module>
  File "/home/administrator/.pyenv/versions/3.8.11/lib/python3.8/site-packages/tb_rest_client-1.1.1-py3.8.egg/tb_rest_client/rest_client_base.py", line 772, in RestClientBase
NameError: name 'TenantProfile' is not defined

**Comment by samson0v** [comment]
Hi @maksonlee, your issue was fixed, please update your rest-client to the newest version via the master branch.

**Comment by maksonlee** [comment]
thanks.
