### ISSUE TITLE
AttributeError: 'RestClientCE' object has no attribute 'auth_controller'

### ISSUE THREAD

**Issue by econeale** [thingsboard/thingsboard-python-rest-client#39]
Attempting to run through the examples using Python 3 on Mac OS and am getting AttributeErrors. All the examples fail but the most recent is: 

```
>>> with RestClientCE(base_url=url) as rest_client:
...     user = rest_client.get_user()
...     print(user)
... 
Traceback (most recent call last):
  File "<stdin>", line 2, in <module>
  File "/usr/local/lib/python3.9/site-packages/tb_rest_client/rest_client_base.py", line 220, in get_user
    return self.auth_controller.get_user_using_get()
AttributeError: 'RestClientCE' object has no attribute 'auth_controller'
```

Version information:
Python 3.9.5 (default, May  4 2021, 03:33:11) 
[Clang 12.0.0 (clang-1200.0.32.29)] on darwin

Installed with ```pip3 install tb-rest-client```

Output of ```pip3 list```: 
```
Package                       Version
----------------------------- ---------
alabaster                     0.7.12
arlo                          1.2.47
attrs                         21.2.0
Babel                         2.9.1
beautifulsoup4                4.9.3
breathe                       4.30.0
bs4                           0.0.1
certifi                       2020.12.5
chardet                       4.0.0
docutils                      0.16
exhale                        0.2.3
idna                          2.10
imagesize                     1.2.0
Jinja2                        3.0.1
jsonschema                    4.2.1
lxml                          4.6.3
MarkupSafe                    2.0.1
monotonic                     1.6
packaging                     20.9
paho-mqtt                     1.5.1
pip                           21.3.1
Pygments                      2.9.0
pyparsing                     2.4.7
pyrsistent                    0.18.0
PySocks                       1.7.1
python-dateutil               2.8.2
pytz                          2021.1
requests                      2.25.1
setuptools                    56.0.0
six                           1.16.0
snowballstemmer               2.1.0
soupsieve                     2.2.1
Sphinx                        4.0.2
sphinx-rtd-theme              0.5.2
sphinxcontrib-applehelp       1.0.2
sphinxcontrib-devhelp         1.0.2
sphinxcontrib-htmlhelp        2.0.0
sphinxcontrib-jsmath          1.0.1
sphinxcontrib-qthelp          1.0.3
sphinxcontrib-serializinghtml 1.1.5
sseclient                     0.0.22
tb-mqtt-client                1.2
tb-rest-client                1.3.2
urllib3                       1.26.4
wheel                         0.36.2
```

**Comment by samson0v** [comment]
Hi @econeale, it seems that you forget to log in.
Try this:
```
with RestClientCE(base_url=url) as rest_client:
    try:
        # Auth with credentials
        rest_client.login(username=username, password=password)
        user = rest_client.get_user()
        print(user)
    except ApiException as e:
        logging.exception(e)
```

**Comment by Anidipta** [comment]
AttributeError: 'RestClient' object has no attribute 'transfer' ?
