### ISSUE TITLE
No module named 'requests'

### ISSUE THREAD

**Issue by apsirmos** [thingsboard/thingsboard-python-rest-client#46]
I installed with pip the tb-rest-client and i have already run the example.py but i take this unexpected error:

`Traceback (most recent call last):
  File "C:\Users\apsir\Desktop\REST API.py", line 1, in <module>
    from tb_rest_client.rest_client_ce import *
  File "C:\Users\apsir\AppData\Local\Programs\Python\Python310\lib\site-packages\tb_rest_client\rest_client_ce.py", line 18, in <module>
    from tb_rest_client.rest_client_base import *
  File "C:\Users\apsir\AppData\Local\Programs\Python\Python310\lib\site-packages\tb_rest_client\rest_client_base.py", line 20, in <module>
    from requests import post
ModuleNotFoundError: No module named 'requests'
`

**Comment by samson0v** [comment]
Hi @apsirmos, `pip install requests`
