### ISSUE TITLE
Incomplete EntityFilter Class

### ISSUE THREAD

**Issue by qwykx** [thingsboard/thingsboard-python-rest-client#55]
**Describe the bug**
When using the example provided on [Python Rest Client - Count entities using Entity Data Query API Example](https://thingsboard.io/docs/reference/python-rest-client/#count-entities-using-entity-data-query-api) this will result in a JSON parse error.

```bash
2022-04-26 09:42:48 - ERROR - Thingsboard_Python_Rest_Example - 38 - (400)
Reason:
HTTP response headers: HTTPHeaderDict({'Date': 'Tue, 26 Apr 2022 07:42:48 GMT', 'Content-Type': 'application/json', 'Transfer-Encoding': 'chunked', 'Connection': 'keep-alive', 'Vary': 'Origin, Access-Control-Request-Method, Access-Control-Request-Headers', 'X-Content-Type-Options': 'nosniff', 'X-XSS-Protection': '1; mode=block', 'Cache-Control': 'no-cache, no-store, max-age=0, must-revalidate', 'Pragma': 'no-cache', 'Expires': '0', 'Strict-Transport-Security': 'max-age=15724800; includeSubDomains'})
HTTP response body: {"status":400,"message":"JSON parse error: Missing type id when trying to resolve subtype of [simple type, class org.thingsboard.server.common.data.query.EntityFilter]: missing type id property 'type' (for POJO property 'entityFilter'); nested exception is com.fasterxml.jackson.databind.exc.InvalidTypeIdException: Missing type id when trying to resolve subtype of [simple type, class org.thingsboard.server.common.data.query.EntityFilter]: missing type id property 'type' (for POJO property 'entityFilter')\n at [Source: (PushbackInputStream); line: 1, column: 19] (through reference chain: org.thingsboard.server.common.data.query.EntityCountQuery[\"entityFilter\"])","errorCode":31,"timestamp":"2022-04-26T07:42:48.286+00:00","subscriptionErrorCode":null,"subscriptionEntry":null,"subscriptionValue":null}
Traceback (most recent call last):
  File "C:\Users\vos\source\repos\Thingsboard Python Rest Example\Thingsboard Python Rest Example\Thingsboard_Python_Rest_Example.py", line 34, in <module>
    devices_count = client.count_entities_by_query(devices_query)
  File "C:\Users\vos\AppData\Local\Programs\Python\Python310\lib\site-packages\tb_rest_client\rest_client_base.py", line 788, in count_entities_by_query
    return self.entity_query_controller.count_entities_by_query_using_post(body=body)
  File "C:\Users\vos\AppData\Local\Programs\Python\Python310\lib\site-packages\tb_rest_client\api\api_ce\entity_query_controller_api.py", line 53, in count_entities_by_query_using_post
    (data) = self.count_entities_by_query_using_post_with_http_info(body, **kwargs)  # noqa: E501
  File "C:\Users\vos\AppData\Local\Programs\Python\Python310\lib\site-packages\tb_rest_client\api\api_ce\entity_query_controller_api.py", line 116, in count_entities_by_query_using_post_with_http_info
    return self.api_client.call_api(
  File "C:\Users\vos\AppData\Local\Programs\Python\Python310\lib\site-packages\tb_rest_client\api_client.py", line 409, in call_api
    return self.__call_api(resource_path, method,
  File "C:\Users\vos\AppData\Local\Programs\Python\Python310\lib\site-packages\tb_rest_client\api_client.py", line 193, in __call_api
    response_data = self.request(
  File "C:\Users\vos\AppData\Local\Programs\Python\Python310\lib\site-packages\tb_rest_client\api_client.py", line 451, in request
    return self.rest_client.POST(url,
  File "C:\Users\vos\AppData\Local\Programs\Python\Python310\lib\site-packages\tb_rest_client\rest.py", line 272, in POST
    return self.request("POST", url,
  File "C:\Users\vos\AppData\Local\Programs\Python\Python310\lib\site-packages\tb_rest_client\rest.py", line 231, in request
    raise ApiException(http_resp=r)
tb_rest_client.rest.ApiException: (400)
Reason:
HTTP response headers: HTTPHeaderDict({'Date': 'Tue, 26 Apr 2022 07:42:48 GMT', 'Content-Type': 'application/json', 'Transfer-Encoding': 'chunked', 'Connection': 'keep-alive', 'Vary': 'Origin, Access-Control-Request-Method, Access-Control-Request-Headers', 'X-Content-Type-Options': 'nosniff', 'X-XSS-Protection': '1; mode=block', 'Cache-Control': 'no-cache, no-store, max-age=0, must-revalidate', 'Pragma': 'no-cache', 'Expires': '0', 'Strict-Transport-Security': 'max-age=15724800; includeSubDomains'})
HTTP response body: {"status":400,"message":"JSON parse error: Missing type id when trying to resolve subtype of [simple type, class org.thingsboard.server.common.data.query.EntityFilter]: missing type id property 'type' (for POJO property 'entityFilter'); nested exception is com.fasterxml.jackson.databind.exc.InvalidTypeIdException: Missing type id when trying to resolve subtype of [simple type, class org.thingsboard.server.common.data.query.EntityFilter]: missing type id property 'type' (for POJO property 'entityFilter')\n at [Source: (PushbackInputStream); line: 1, column: 19] (through reference chain: org.thingsboard.server.common.data.query.EntityCountQuery[\"entityFilter\"])","errorCode":31,"timestamp":"2022-04-26T07:42:48.286+00:00","subscriptionErrorCode":null,"subscriptionEntry":null,"subscriptionValue":null}
```
**Reason**
The _EntityFilter() Class_ is incomplete - it is missing all required properties/attributes. It seems that the swagger definition does not specify the model and therefore the generated code is missing stuff.

Cheers

**Comment by samson0v** [comment]
Hi @qwykx, update your rest client to the newest version via the master branch and let us know if it helps.
