### ISSUE TITLE
Unable to create customer

### ISSUE THREAD

**Issue by hlavacek87** [thingsboard/thingsboard-python-rest-client#88]
Hello, it seems that your examples within repository dont work at all. 

With release 1.4 I am able create Customer/User/Role but not the Group Entity. With the latest version of master branch I am able to create Group but not the Customer.

TB version: PE 3.4.1
Python: 3.8.12
OS: Rocky8
tb python client version: lastest master

`
tenant_id = current_user.tenant_id
customer1 = Customer(title="Customer1", tenant_id = current_user.tenant_id, country="US", state="US", address="", address2="", city="NY", email="", phone="", zip="" )
customer1 = rest_client.save_customer(customer1)
logging.info("Customer was created:\n%r\n", customer1)
`

ERROR:
`
Reason:
HTTP response headers: HTTPHeaderDict({'vary': 'Origin, Access-Control-Request-Method, Access-Control-Request-Headers', 'x-content-type-options': 'nosniff', 'x-xss-protection': '1; mode=block', 'cache-control': 'no-cache, no-store, max-age=0, must-revalidate', 'pragma': 'no-cache', 'expires': '0', 'content-type': 'application/json;charset=ISO-8859-1', 'content-length': '200', 'date': 'Wed, 19 Oct 2022 12:06:17 GMT'})
HTTP response body: b'{"status":400,"message":"Customer title should be specified!","errorCode":31,"timestamp":"2022-10-19T12:06:17.270+00:00","subscriptionErrorCode":null,"subscriptionEntry":null,"subscriptionValue":null}'
Traceback (most recent call last):
  File "./example_application_2.py", line 78, in main
    customer1 = rest_client.save_customer(customer1)
  File "/root/tb/myenv/thingsboard-python-rest-client/tb_rest_client/rest_client_pe.py", line 362, in save_customer
    return self.customer_controller.save_customer_using_post(entity_group_id=entity_group_id, body=body)
  File "/root/tb/myenv/thingsboard-python-rest-client/tb_rest_client/api/api_pe/customer_controller_api.py", line 978, in save_customer_using_post
    (data) = self.save_customer_using_post_with_http_info(**kwargs)  # noqa: E501
  File "/root/tb/myenv/thingsboard-python-rest-client/tb_rest_client/api/api_pe/customer_controller_api.py", line 1041, in save_customer_using_post_with_http_info
    return self.api_client.call_api(
  File "/root/tb/myenv/thingsboard-python-rest-client/tb_rest_client/api_client.py", line 401, in call_api
    return self.__call_api(resource_path, method,
  File "/root/tb/myenv/thingsboard-python-rest-client/tb_rest_client/api_client.py", line 193, in __call_api
    response_data = self.request(
  File "/root/tb/myenv/thingsboard-python-rest-client/tb_rest_client/api_client.py", line 443, in request
    return self.rest_client.POST(url,
  File "/root/tb/myenv/thingsboard-python-rest-client/tb_rest_client/rest.py", line 263, in POST
    return self.request("POST", url,
  File "/root/tb/myenv/thingsboard-python-rest-client/tb_rest_client/rest.py", line 222, in request
    raise ApiException(http_resp=r)
tb_rest_client.rest.ApiException: (400)
Reason:
HTTP response headers: HTTPHeaderDict({'vary': 'Origin, Access-Control-Request-Method, Access-Control-Request-Headers', 'x-content-type-options': 'nosniff', 'x-xss-protection': '1; mode=block', 'cache-control': 'no-cache, no-store, max-age=0, must-revalidate', 'pragma': 'no-cache', 'expires': '0', 'content-type': 'application/json;charset=ISO-8859-1', 'content-length': '200', 'date': 'Wed, 19 Oct 2022 12:06:17 GMT'})
HTTP response body: b'{"status":400,"message":"Customer title should be specified!","errorCode":31,"timestamp":"2022-10-19T12:06:17.270+00:00","subscriptionErrorCode":null,"subscriptionEntry":null,"subscriptionValue":null}'
`

**Comment by samson0v** [comment]
Hi @hlavacek87, it seems that there is no problem:
```
customer = Customer(title='Test', name='Test')
customer = rest_client.save_customer(body=customer)
print(customer)
```
<img width="442" alt="зображення" src="https://user-images.githubusercontent.com/43861229/201914981-d4870122-d3af-41d6-ad14-8f71549a3930.png">

**Comment by hlavacek87** [comment]
Hello, I have used same code as you but no luck. Have you tried PE version of TB? I am using master branch, freshly cloned.

```
import logging
from json import load
# Importing models and REST client class from Professional Edition version
from tb_rest_client.rest_client_pe import *
from tb_rest_client.rest import ApiException

logging.basicConfig(level=logging.DEBUG,
                    format='%(asctime)s - %(levelname)s - %(module)s - %(lineno)d - %(message)s',
                    datefmt='%Y-%m-%d %H:%M:%S')

# ThingsBoard REST API URL
url = "http://localhost:8080"

# Default Tenant Administrator credentials
username = "tenant@thingsboard.org"
password = "tenant"

# Creating the REST client object with context manager to get auto token refresh
def main():
    with RestClientPE(base_url=url) as rest_client:
        try:
            # Auth with credentials
            rest_client.login(username=username, password=password)

            # Getting current user
            current_user = rest_client.get_user()

            # Creating Customer 1
            customer1 = Customer(title="Customer 1", name="Customer 1")
            customer1 = rest_client.save_customer(body=customer1)
       
        except ApiException as e:
            logging.exception(e)

if __name__ == '__main__':
    main()
```

Console output:
```
SNDBX  examples # python ./example_application_2_mh.py
Traceback (most recent call last):
  File "./example_application_2_mh.py", line 63, in <module>
    main()
  File "./example_application_2_mh.py", line 51, in main
    customer1 = Customer(title="Customer 1", name="Customer 1")
  File "/usr/local/lib/python3.8/site-packages/tb_rest_client/models/models_pe/customer.py", line 103, in __init__
    self.tenant_id = tenant_id
  File "/usr/local/lib/python3.8/site-packages/tb_rest_client/models/models_pe/customer.py", line 251, in tenant_id
    raise ValueError("Invalid value for `tenant_id`, must not be `None`")  # noqa: E501
ValueError: Invalid value for `tenant_id`, must not be `None`
```

NOTE: adding tenant_id helps but raise another problem that Country is not filled in .... filling all have the same result as above
